### ISSUE TITLE
ToISOString breaking dates

### ISSUE THREAD

**Issue by jjacobson** [DataTables/SearchBuilder#6]
https://github.com/DataTables/SearchBuilder/blob/2a3ceb327baf397ff5522088facd1f9db8c8d2f9/src/criteria.ts#L2044

This line is causing me a headache. This converts the date to an ISO string ex. "2022-01-16T09:00:00.000Z"

The next time you make a request to the server it tries to create a moment date using that ISO string along with your custom formatter. This results in an invalid date because the custom format doesn't line up with that date.

**Comment by SandyDatatables** [comment]
Hi @jjacobson ,

This sounds to me like an issue with the server side implementation? Is that where the error is occurring?

Either way, as mentioned in your [forum post](https://datatables.net/forums/discussion/71327/date-field-issue-for-nightly-builds-searchbuilder-version#latest), please can you link to a test case so that we can actually see the issue occurring. Information on how to create a test case (if you aren't able to link to the page you are working on) is [available here](/tn/10).

Thanks,
Sandy

PS. We prefer please if you find an issue to raise it in the forum. That is our preferred way of tracking them and keeps everything in one place for us :)

**Comment by jjacobson** [comment]
Copying my response here for history:

No, this is client side. Take a look at the requests made to the server in this example. 
http://live.datatables.net/macizuwa/19/edit
Specifically once you set a date and then try to page through the table. Note the format that I've set:

"$.fn.dataTable.moment('MM/DD/YYYY');"

Request #1 to the server when selecting a date:

![image](https://user-images.githubusercontent.com/2087892/154531504-b76f6d0d-299f-427c-b264-75f89c9dd42d.png)


After selecting the next page:
![image](https://user-images.githubusercontent.com/2087892/154531560-c7df2931-2187-4f36-aece-35e54a02266e.png)


If you are going to call toISOString (which makes sense for sorting the two values prior to the request) you can't call it again using the custom format during later requests because moment then tries to parse the ISO date using my format, which is not in ISO.
